version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: iot_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - webapp
    networks:
      - iot_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email oab084@gmail.com -d airkfh.xyz --agree-tos

  mongodb:
    image: mongo
    container_name: iot_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB:-iotdb}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - /etc/localtime:/etc/localtime:ro
    networks:
      - iot_network
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  subscriber:
    build: ./subscriber
    container_name: iot_subscriber
    depends_on:
      - mongodb
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keycredentials.json
    restart: always

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    #container_name: iot_webapp
    restart: no
    env_file:
      - .env
    deploy:
      replicas: 3

    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - MONGODB_DB=${MONGODB_DB}
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - APP_TITLE=${APP_TITLE:-IoT Management Web}
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongodb
    networks:
      - iot_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/app

    command: "/app/scripts/run-web-docker"

    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  iot_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
