version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: iotdb_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB:-iotdb}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - /etc/localtime:/etc/localtime:ro
    networks:
      - iot_network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  webapp:
    build: .
    ports:
      - "8080:8080"
    container_name: iotdb_webapp
    restart: no
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - MONGODB_DB=${MONGODB_DB}
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - APP_TITLE=${APP_TITLE:-IoT Management Web}
    depends_on:
      - mongodb
    networks:
      - iot_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/app
    command:
      "/app/scripts/run-web-docker"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

#Note: other app 10.0.11.0/24 10.0.12.0/24

#  nginx:
#    image: nginx:alpine
#    container_name: iotdb_nginx
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - webapp
#    networks:
#      - iot_network

networks:
  iot_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
