name: Deploy to GCE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: debug SSH Key
        run: |
          echo "$SSH_AUTH_SOCK"
          ls -l $SSH_AUTH_SOCK
      - name: Debug GCE_VM_IP
        run: echo "GCE_VM_IP is ${{ secrets.GCE_VM_IP }}"
        
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCE_VM_IP }}
          username: ${{ secrets.GCE_SSH_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          debug: true
          script: |
            cd /home/sda_project
            docker compose down
            git pull origin main
            docker compose up -d --build